"""Add fulfillment status to OrderItem

Revision ID: ce9847360e95
Revises: e2e30458d496
Create Date: 2025-08-16 01:49:22.353596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9847360e95'
down_revision = 'e2e30458d496'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fulfillment_status', sa.Enum('UNFULFILLED', 'SHIPPED', 'DELIVERED', 'CANCELED', name='orderitemstatus'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_column('fulfillment_status')

    # ### end Alembic commands ###
